### PR TITLE
Io2021 c 72 request authentication

### PR DESCRIPTION
**Pull request by ChrisMisan**
Goal of this draft is to present preview of request authentication system before it is introduced to the rest of the project. Currently request authentication is implemented in two layers:
~~- Controller layer, which is responsible for auth that does not require fetching from database - save/update/delete, all scenarios where we could immediatly check for permissions~~
- Database layer, which is responsible for fetching only available data - when user A is requesting list of all users he'll only obtain users who are listed in his read permissions

All controller side authentication was moved to corresponding services. 
All affected tests were also updated.
For the relevant code please refer to ~~450aded3aee8489d145e10b32aa5a946a340ff84 2981ca3aa00c66fe741187b62d10de6c1150a6d7 91e318739aff2e0142f4cfaa143e084c59990227 296a78409d6714486ac8bf831e7e236852033cef~~d842c9a684403ad1bbe11428fce6f98b718d66b5 7c7e3d4c0e753b17fb1f37c993fa8ad68113cb6b

### CODE REVIEW

**Comment by ChrisFlam3** [comment]
It is being reworked to move all auth to service level.

**Comment by ChrisMisan** [comment]
Auth was restructured, it is now encapsulated in db-service layer.

**Review by Pinioo — APPROVED** [review]
Looks fine

**Comment by ChrisMisan** [comment]
PR ready to merge

**Pull request merged**
